---
Gain: 1.6
RN: 10.0
TemperatureDeadband: 0.5
RawFileExt: 0

MasterPath: '/Volumes/Drobo/V5/Master'
MasterBiasRootName: 'MasterBias_'
MasterDarkRootName: 'MasterDark_'
MasterFlatRootName: 'MasterFlat_'
MasterShutterMapRootName: 'ShutterMap_'

BiasPath: '/Volumes/Drobo/V5/Images/[YYYYMMDDUT]/Calibration'
DarkPath: '/Volumes/Drobo/V5/Images/[YYYYMMDDUT]/Calibration'
FlatPath: '/Volumes/Drobo/V5/Images/[YYYYMMDDUT]/AutoFlat'
CalsWindow: 10  # Size of window (in days) prior to an image's date for which
                # biases and darks are considered relevant to that image
FlatsWindow: 10 # Size of window (in days) prior to an image's date for which
                # flats are considered relevant to that image

